[features]
seeds = false
skip-lint = false
[programs.localnet]
onchain_voting_anchor_program = "3K6e8zTsXtBatEJf9tDmXNm91PHpEZmHGcNxhrMEiB4F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/fuujack/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test]
startup_wait = 10000